### ISSUE TITLE
Symfony flex support

### ISSUE THREAD

**Issue by nervo** [manala/manalize#138]
- [x] `web/app_*.php` -> `public/index.php`(ansible nginx, deploy)
- [x] `/var/logs`-> `/var/log`
- [x] Drop `/var/sessions`(ansible files)
- [x] Env (`SYMFONY_ENV` -> `APP_ENV`)

**Comment by tristanbes** [comment]
do want this ! 🤓 😍

**Comment by tristanbes** [comment]
Maybe I'm wrong, but why drop `/var/sessions` when it's still the default path used to store sessions ?

https://symfony.com/doc/current/session/sessions_directory.html

**Comment by ogizanagi** [comment]
@tristanbes : Right, but starting to symfony 3.4 with flex, the default is to use the native session handler (`php.ini` declared one), so this is not needed by default.

**Comment by tristanbes** [comment]
ok, my bad, the doc didn't reflect that.

**Comment by tristanbes** [comment]
For other reading this issue, you can get an app based on Flex work out of the box with
```yml
// app.yml
  nginx_configs:
    - file:     app_php_fpm
      template: configs/app_php_fpm.{{ env }}.j2
    - file:     app_gzip
      template: configs/app_gzip.{{ env }}.j2
    # App
    - file: app.conf
      config:
        - server:
          - server_name: "{{ app.host }}"
          - root:        "{{ app.dir }}{{ app.dir_release }}/public"
          - access_log:  "{{ app.log_dir }}/nginx.access.log"
          - error_log:   "{{ app.log_dir }}/nginx.error.log"
          - include:     conf.d/app_gzip
          - location /:
            - try_files: $uri /index.php$is_args$args
          - location ~ ^/index\.php(/|$):
            - include: conf.d/app_php_fpm
```
