### ISSUE TITLE
Symfony gc_probability on debian

### ISSUE THREAD

**Issue by maximecolin** [manala/manalize#146]
By default, Symfony set `gc_probability` to 1 and override php ini. On debian with sury php, a cron job clean the session instead of php session garbage collector. So we need to set `gc_probability` to `~` to tell Symfony to not override the default php config (`0`).

```yml
framework:
    session:
        # Don't override php gc_probability config
        gc_probability: ~
```
