### ISSUE TITLE
mkcert to use HTTPS in local

### ISSUE THREAD

**Issue by tristanbes** [manala/manalize#147]
Hi ✌️

Wouldn't be cool if mana could generate the HTTPS certs for local environement using this integration ? 

https://github.com/FiloSottile/mkcert

🍒 Kisses ;-)

**Comment by nervo** [comment]
@tristanbes we already have something like that.
An auto-signed certificate is generated for each vm in `/etc/ssl/certs/ssl-cert-snakeoil.pem`. You can use it with the related offloading nginx template: https://github.com/manala/ansible-roles/blob/master/manala.nginx/templates/configs/app_ssl_offloading.dev.j2

Btw, we can enhance a bit, by providing a command to export it in a glamour way.
Any idea ?

**Comment by tristanbes** [comment]
So instead of:
```yml
  nginx_configs:
    - file: app.conf
      config: ...
```
I should do 
```yml
  nginx_configs:
    - file: app_ssl_offloading.conf
      config: ...
```

Is the certificate wildcard ? 
What happens if it's not wildcard and we have `api.foo.vm` and `admin.foo.vm`

Is the certificate generated when running `make setup` ? 

Thanks :-)
